version: '3.9'

services:

  mysql:
    image: mysql:8.0.34
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      #      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - ./docker/mysql:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: miniorootuser
      MINIO_ROOT_PASSWORD: miniorootuser
      MINIO_HTTP_TRACE: /dev/stdout
    command: server --console-address ":9001" /data

  backend-app:
    hostname: backend-app
    build:
      context: ./backend-nestjs
      dockerfile: Dockerfile
    image: backend-app:latest
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - MINIO_HOST=minio
      - MINIO_PORT=9000
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - minio
    # volumes:
    #   - ./docker/backend-app/.env:/usr/src/app/.env

  nginx:
    hostname: nginx
    image: nginx:alpine3.18-slim
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/www:/var/www/certbot/:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro

volumes:
  mysql-data:
  minio-data:
