version: "3.8"

services:
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: miniorootuser
      MINIO_ROOT_PASSWORD: miniorootuser
      MINIO_HTTP_TRACE: /dev/stdout
    command: server --console-address ":9001" /data

volumes:
  minio-data:
