name: Trigger Build And Deploy Backend

on:
  push:
    branches:
      - backend
#    paths:
#      - backend-nestjs/**

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
